# Generated by Django 4.2.6 on 2023-10-09 14:14

from django.db import migrations


def create_data(apps, schema_editor):
    Student = apps.get_model("students", "Student")
    Student(name="Joe Silver", email="joe@email.com", document="2223333222", phone="123123").save()


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_data)]
