version: "3.8"

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    image: vue-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    tty: true

  backend:
    build: ./backend
    # image: django-backend
    # restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
