# Generated by Django 4.2.6 on 2023-10-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="CocktailRecipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("ingredients", models.JSONField(verbose_name="Ingredients")),
                ("steps", models.JSONField(verbose_name="Steps")),
            ],
        ),
    ]
