# Generated by Django 4.2.6 on 2023-10-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cocktailRecipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktailrecipe",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
