# Generated by Django 4.2.6 on 2023-10-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cocktailRecipes", "0002_alter_cocktailrecipe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktailrecipe",
            name="ingredients",
            field=models.JSONField(default=list, verbose_name="Ingredients"),
        ),
        migrations.AlterField(
            model_name="cocktailrecipe",
            name="steps",
            field=models.JSONField(default=list, verbose_name="Steps"),
        ),
    ]
